nginx:
    build: ./build/nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/template/default:/etc/nginx/sites-available/default
        - ./nginx/template/default:/etc/nginx/sites-enabled/default

        - ./nginx/logs/nginx-error.log:/var/log/nginx/error.log
        - ./nginx/logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    build: ./build/php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html
mysql_db:
    build: ./build/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty13q
    ports:
      - "3306:3306"
    volumes:
        - ./database:/var/lib/mysql
          
adminer: 
    build: ./build/adminer
    restart: always 
    ports:   
        - 8090:8080
    links:   
        - mysql_db

phpmyadmin: 
    build: ./build/phpmyadmin
    restart: always
    ports:
        - 8080:80
    links:
        - mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: qwerty13q
      PMA_ARBITRARY: 1