nginx_phpfpm:
    build: ./nginx_phpfpm
    ports:
        - "80:80"
    links:
        - db_mysql
    volumes:
        - ./nginx_phpfpm/template/default:/etc/nginx/sites-enable/default
        - ./nginx_phpfpm/template/default:/etc/nginx/sites-available/default
        - ./nginx_phpfpm/logs/nginx-error.log:/var/log/nginx/error.log
        - ./nginx_phpfpm/logs/nginx-access.log:/var/log/nginx/access.log
        - ./nginx_phpfpm/logs/drupal_error.log:/var/log/nginx/drupal_error.log
        - ./nginx_phpfpm/logs/drupal-access.log:/var/log/nginx/drupal_access.log

db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
        - "3306:3306"
    volumes:
        - ./database:/var/lib/mysql

phpmyadmin: 
    image: phpmyadmin:phpmyadmin
    restart: always
    ports:
        - 8080:80
    links:
        - db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      PMA_ARBITRARY: 1